### ISSUE TITLE
LCD showing weird characters on raspberry pi when I boot from  .bashrc

### ISSUE THREAD

**Issue by nugoo1** [fivdi/lcd#19]
It works completely fine when I run it normally, i.e. when i run node myApp.js from the terminal.

The problem only occurs when I run the program at boot by adding the command node myApp.js to the last line of  .bashrc txt file... The lcd works to display the first two messages, actually but when I run a loop where the user presses a button - - lcd is supposed to show some user feedback, but the characters are all weird...

Again it runs fine when I run the app from the terminal....

**Comment by fivdi** [comment]
.bashrc is a shell script that bash runs whenever it is started interactively. .bashrc is not a shell script that is only run once at boot time. Every time a terminal window is opened .bashrc will be run.

Perhaps bash was started interactively multiple times on your system, for example, by opening multiple terminals and the Node.js program controlling the LCD was therefore also started multiple times. 

If the Node.js program controlling the LCD is running multiple times the different instances of the program will end up interfering with each other.

Run the command `"ps -A | grep node"` to see how many node processes are running. `"ps -Af | grep node"` will show mode details.

It may be better to run the Node.js program controlling the LCD as a service with systemd.

**Comment by nugoo1** [comment]
Thanks fivdi, yes from all the tutorials it seems like adding it as a service is the best way to go if I want to run on boot. Thanks for your help!
