### ISSUE TITLE
configuration issue with i2c on raspberry pi 2 model b

### ISSUE THREAD

**Issue by wiulma** [fivdi/lcd#26]
Hi, is it possibile to use this module on a raspberry pi 2, with a i2c connector? 
I can't make it working...i'm sure it's a configuration error about gpio pins.
I'm reading this tutorial
`https://tutorials-raspberrypi.com/control-a-raspberry-pi-hd44780-lcd-display-via-i2c/`

I have 4 gpio (gnd, vcc, sda, scl) but i can't configure the lcd constructor in the right way.
Do you have any suggestions?

thanks!

**Comment by fivdi** [comment]
> Hi, is it possibile to use this module on a raspberry pi 2, with a i2c connector?

Hi @wiulma, no it is not possible to use this module with an i2c connector. It is only possible to use this module with the LCDs parallel interface. See [here](https://github.com/fivdi/lcd#lcd).
